name: Codacy Analysis

on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
